const resources = [
  // ========== AI 工具 ==========
  { name: 'ChatGPT', desc: 'OpenAI 推出的最强 AI 对话助手，支持写作、编程、分析等', url: 'https://chat.openai.com', cat: 'ai', tag: '对话', hot: true },
  { name: 'Claude', desc: 'Anthropic 推出的 AI 助手，擅长长文本处理与深度分析', url: 'https://claude.ai', cat: 'ai', tag: '对话', hot: true },
  { name: 'Kimi', desc: '月之暗面出品，支持超长上下文（200万字）的 AI 助手', url: 'https://kimi.moonshot.cn', cat: 'ai', tag: '对话', hot: true },
  { name: '通义千问', desc: '阿里云出品的大语言模型，支持文档理解、代码生成', url: 'https://tongyi.aliyun.com', cat: 'ai', tag: '对话' },
  { name: '文心一言', desc: '百度出品的大语言模型，支持中文对话与内容生成', url: 'https://yiyan.baidu.com', cat: 'ai', tag: '对话' },
  { name: 'DeepSeek', desc: '深度求索出品的高性能 AI 模型，推理能力强', url: 'https://chat.deepseek.com', cat: 'ai', tag: '对话', hot: true },
  { name: '豆包', desc: '字节跳动出品的 AI 助手，支持多轮对话', url: 'https://www.doubao.com', cat: 'ai', tag: '对话' },
  { name: 'Gemini', desc: 'Google 推出的多模态 AI 模型', url: 'https://gemini.google.com', cat: 'ai', tag: '对话' },
  { name: 'Midjourney', desc: '顶尖 AI 绘画工具，通过文本描述生成高质量图片', url: 'https://www.midjourney.com', cat: 'ai', tag: '绘画', hot: true },
  { name: 'Stable Diffusion', desc: '开源 AI 图像生成模型，可本地部署', url: 'https://stability.ai', cat: 'ai', tag: '绘画' },
  { name: 'DALL·E 3', desc: 'OpenAI 的 AI 绘图工具，集成在 ChatGPT 中', url: 'https://openai.com/dall-e-3', cat: 'ai', tag: '绘画' },
  { name: '可灵 AI', desc: '快手出品的 AI 视频生成工具', url: 'https://kling.kuaishou.com', cat: 'ai', tag: '视频' },
  { name: 'Runway Gen-2', desc: 'AI 视频生成工具，支持文字/图片生成视频', url: 'https://runwayml.com', cat: 'ai', tag: '视频' },
  { name: '剪映', desc: '字节跳动出品的一站式视频剪辑工具，内置 AI 功能', url: 'https://www.capcut.cn', cat: 'ai', tag: '视频', hot: true },
  { name: 'Notion AI', desc: '集成 AI 能力的笔记与协作平台', url: 'https://www.notion.so', cat: 'ai', tag: '写作' },
  { name: 'Gamma', desc: 'AI 驱动的 PPT/文档生成工具', url: 'https://gamma.app', cat: 'ai', tag: '办公' },
  { name: 'Perplexity', desc: 'AI 搜索引擎，提供带引用的深度答案', url: 'https://www.perplexity.ai', cat: 'ai', tag: '搜索', hot: true },

  // ========== 设计资源 ==========
  { name: 'Canva', desc: '在线平面设计平台，海量模板轻松制作海报/简历/PPT', url: 'https://www.canva.com', cat: 'design', tag: '平面', hot: true },
  { name: 'Figma', desc: '协作式 UI/UX 设计工具，浏览器即可使用', url: 'https://www.figma.com', cat: 'design', tag: 'UI' },
  { name: 'MasterGo', desc: '国产协作 UI 设计工具，Figma 替代品', url: 'https://mastergo.com', cat: 'design', tag: 'UI' },
  { name: 'Pixso', desc: '国产在线 UI 设计工具，支持团队协作', url: 'https://pixso.cn', cat: 'design', tag: 'UI' },
  { name: 'Unsplash', desc: '高质量免费可商用图片库，摄影作品丰富', url: 'https://unsplash.com', cat: 'design', tag: '图库', hot: true },
  { name: 'Pexels', desc: '免费可商用图片与视频素材库', url: 'https://www.pexels.com', cat: 'design', tag: '素材' },
  { name: 'Pixabay', desc: '免费图片、视频、音乐素材库', url: 'https://pixabay.com', cat: 'design', tag: '素材' },
  { name: 'IconFont', desc: '阿里巴巴矢量图标库，海量免费图标', url: 'https://www.iconfont.cn', cat: 'design', tag: '图标', hot: true },
  { name: 'Flaticon', desc: '免费矢量图标库，支持 SVG/PNG 下载', url: 'https://www.flaticon.com', cat: 'design', tag: '图标' },
  { name: 'Freepik', desc: '免费矢量图、PSD、图标、插画素材', url: 'https://www.freepik.com', cat: 'design', tag: '素材' },
  { name: 'ColorHub', desc: '免费高清图片集，分类清晰', url: 'https://colorhub.me', cat: 'design', tag: '图库' },
  { name: 'Coolors', desc: '在线配色方案生成工具', url: 'https://coolors.co', cat: 'design', tag: '配色' },
  { name: 'Remove.bg', desc: 'AI 一键去除图片背景', url: 'https://www.remove.bg', cat: 'design', tag: '图片处理', hot: true },
  { name: '稿定设计', desc: '国内在线设计平台，模板丰富适合新媒体', url: 'https://www.gaoding.com', cat: 'design', tag: '平面' },

  // ========== 开发工具 ==========
  { name: 'GitHub', desc: '全球最大的代码托管平台，开源项目聚集地', url: 'https://github.com', cat: 'dev', tag: '代码托管', hot: true },
  { name: 'Gitee', desc: '国内代码托管平台，访问速度快', url: 'https://gitee.com', cat: 'dev', tag: '代码托管' },
  { name: 'VSCode', desc: '微软出品的免费代码编辑器，插件生态丰富', url: 'https://code.visualstudio.com', cat: 'dev', tag: '编辑器', hot: true },
  { name: 'WebStorm', desc: 'JetBrains 出品的前端开发 IDE', url: 'https://www.jetbrains.com/webstorm', cat: 'dev', tag: '编辑器' },
  { name: 'CodePen', desc: '在线前端代码编辑器，适合快速原型', url: 'https://codepen.io', cat: 'dev', tag: '在线编码' },
  { name: 'StackBlitz', desc: '在线 IDE，支持 Angular/React/Vue 项目', url: 'https://stackblitz.com', cat: 'dev', tag: '在线编码' },
  { name: 'JSFiddle', desc: '在线 HTML/CSS/JS 代码测试工具', url: 'https://jsfiddle.net', cat: 'dev', tag: '在线编码' },
  { name: 'JSON.cn', desc: 'JSON 格式化/验证/压缩工具', url: 'https://www.json.cn', cat: 'dev', tag: '工具' },
  { name: '正则大全', desc: '常用正则表达式汇总与测试工具', url: 'https://any86.github.io/any-rule', cat: 'dev', tag: '工具' },
  { name: 'Can I Use', desc: '查询 CSS/JS 特性在各浏览器兼容性', url: 'https://caniuse.com', cat: 'dev', tag: '兼容性' },
  { name: 'DevDocs', desc: '开发者文档聚合，离线可用', url: 'https://devdocs.io', cat: 'dev', tag: '文档' },
  { name: 'Oh My Zsh', desc: '终端增强框架，美化命令行', url: 'https://ohmyz.sh', cat: 'dev', tag: '终端' },
  { name: 'Postman', desc: 'API 调试工具，支持接口测试与文档', url: 'https://www.postman.com', cat: 'dev', tag: 'API' },
  { name: 'Swagger', desc: 'API 设计/文档/测试工具', url: 'https://swagger.io', cat: 'dev', tag: 'API' },
  { name: 'npm', desc: 'Node.js 包管理器，海量开源库', url: 'https://www.npmjs.com', cat: 'dev', tag: '包管理' },
  { name: 'Vercel', desc: '前端部署平台，支持自动部署', url: 'https://vercel.com', cat: 'dev', tag: '部署', hot: true },
  { name: 'Netlify', desc: '静态网站托管平台，支持 CI/CD', url: 'https://www.netlify.com', cat: 'dev', tag: '部署' },
  { name: 'Railway', desc: '全栈部署平台，支持多种语言', url: 'https://railway.app', cat: 'dev', tag: '部署' },

  // ========== 在线学习 ==========
  { name: '中国大学MOOC', desc: '国内顶尖高校课程平台，免费旁听', url: 'https://www.icourse163.org', cat: 'learn', tag: '综合', hot: true },
  { name: 'Bilibili', desc: '海量编程/设计/职场教学视频', url: 'https://www.bilibili.com', cat: 'learn', tag: '综合', hot: true },
  { name: 'Coursera', desc: '全球名校在线课程，可拿证书', url: 'https://www.coursera.org', cat: 'learn', tag: '国际' },
  { name: 'Udemy', desc: '付费课程平台，覆盖 IT/设计/营销等', url: 'https://www.udemy.com', cat: 'learn', tag: '国际' },
  { name: 'freeCodeCamp', desc: '免费学编程，含交互式练习与项目', url: 'https://www.freecodecamp.org', cat: 'learn', tag: '编程' },
  { name: '菜鸟教程', desc: '国内最受欢迎的编程入门教程站', url: 'https://www.runoob.com', cat: 'learn', tag: '编程', hot: true },
  { name: 'MDN Web Docs', desc: '最权威的 Web 开发文档', url: 'https://developer.mozilla.org', cat: 'learn', tag: '文档' },
  { name: 'W3Schools', desc: 'Web 开发入门教程，在线练习', url: 'https://www.w3schools.com', cat: 'learn', tag: '编程' },
  { name: 'Stack Overflow', desc: '全球最大编程问答社区', url: 'https://stackoverflow.com', cat: 'learn', tag: '社区' },
  { name: '掘金', desc: '中文技术社区，优质前端/后端/AI 文章', url: 'https://juejin.cn', cat: 'learn', tag: '社区', hot: true },
  { name: '知乎', desc: '深度知识问答社区，技术/职场/成长', url: 'https://www.zhihu.com', cat: 'learn', tag: '社区' },
  { name: '慕课网', desc: '国内 IT 技能学习平台，实战导向', url: 'https://www.imooc.com', cat: 'learn', tag: '编程' },
  { name: 'Kaggle', desc: '数据科学/机器学习竞赛与学习平台', url: 'https://www.kaggle.com', cat: 'learn', tag: '数据' },
  { name: 'LabEx', desc: '在线 Linux/DevOps 实验环境', url: 'https://labex.io', cat: 'learn', tag: '运维' },
  { name: 'LeetCode', desc: '程序员刷题备战面试必备', url: 'https://leetcode.cn', cat: 'learn', tag: '算法', hot: true },

  // ========== 效率工具 ==========
  { name: 'Notion', desc: '一站式笔记/知识库/项目管理工具', url: 'https://www.notion.so', cat: 'productivity', tag: '笔记', hot: true },
  { name: '飞书', desc: '字节跳动出品的企业协作平台，含文档/日历/会议', url: 'https://www.feishu.cn', cat: 'productivity', tag: '协作', hot: true },
  { name: 'Trello', desc: '看板式项目管理工具，简单直观', url: 'https://trello.com', cat: 'productivity', tag: '项目管理' },
  { name: 'ProcessOn', desc: '在线流程图/思维导图工具', url: 'https://www.processon.com', cat: 'productivity', tag: '思维导图' },
  { name: 'XMind', desc: '专业思维导图软件', url: 'https://www.xmind.cn', cat: 'productivity', tag: '思维导图' },
  { name: '石墨文档', desc: '国内在线协作文档平台', url: 'https://shimo.im', cat: 'productivity', tag: '文档' },
  { name: '语雀', desc: '阿里出品的企业知识管理平台', url: 'https://www.yuque.com', cat: 'productivity', tag: '笔记' },
  { name: '滴答清单', desc: '跨平台待办事项与时间管理工具', url: 'https://dida365.com', cat: 'productivity', tag: '待办' },
  { name: 'Todoist', desc: '全球流行的待办事项管理工具', url: 'https://todoist.com', cat: 'productivity', tag: '待办' },
  { name: 'Forest', desc: '专注计时器，种树戒掉手机', url: 'https://www.forestapp.cc', cat: 'productivity', tag: '专注' },
  { name: 'Chrome', desc: 'Google 浏览器，插件生态最丰富', url: 'https://www.google.com/chrome', cat: 'productivity', tag: '浏览器' },
  { name: 'Tampermonkey', desc: '浏览器脚本管理器，安装各类增强脚本', url: 'https://www.tampermonkey.net', cat: 'productivity', tag: '浏览器' },
  { name: 'uBlock Origin', desc: '高效的广告拦截浏览器插件', url: 'https://ublockorigin.com', cat: 'productivity', tag: '浏览器' },
  { name: 'Snipaste', desc: '截图+贴图工具，开发/设计必备', url: 'https://www.snipaste.com', cat: 'productivity', tag: '截图' },
  { name: 'Everything', desc: 'Windows 最强文件搜索工具', url: 'https://www.voidtools.com', cat: 'productivity', tag: '搜索' },

  // ========== 写作/内容创作 ==========
  { name: '石墨文档', desc: '国内最早的在线协作文档之一', url: 'https://shimo.im', cat: 'writing', tag: '文档' },
  { name: 'Grammarly', desc: 'AI 英文写作助手，语法检查与润色', url: 'https://www.grammarly.com', cat: 'writing', tag: '英文' },
  { name: 'DeepL', desc: '最准确的 AI 翻译工具', url: 'https://www.deepl.com', cat: 'writing', tag: '翻译', hot: true },
  { name: '百度翻译', desc: '百度出品的多语种翻译平台', url: 'https://fanyi.baidu.com', cat: 'writing', tag: '翻译' },
  { name: 'Hemingway App', desc: '英文写作风格优化工具', url: 'https://hemingwayapp.com', cat: 'writing', tag: '英文' },
  { name: '新媒体管家', desc: '公众号/头条号运营辅助工具', url: 'https://xmt.cn', cat: 'writing', tag: '运营' },
  { name: '135编辑器', desc: '公众号图文排版工具', url: 'https://www.135editor.com', cat: 'writing', tag: '排版' },
  { name: '文案狗', desc: 'AI 辅助文案生成，广告语/Slogan', url: 'https://www.wenango.com', cat: 'writing', tag: '文案' },

  // ========== 免费素材 ==========
  { name: 'Unsplash', desc: '高质量免费可商用图片', url: 'https://unsplash.com', cat: 'free', tag: '图片' },
  { name: 'Pexels', desc: '免费图片与视频素材', url: 'https://www.pexels.com', cat: 'free', tag: '媒体' },
  { name: 'Pixabay', desc: '免费图片/视频/音乐/音效', url: 'https://pixabay.com', cat: 'free', tag: '媒体' },
  { name: 'Mixkit', desc: '免费视频素材与动画模板', url: 'https://mixkit.co', cat: 'free', tag: '视频' },
  { name: 'Coverr', desc: '免费商用视频素材', url: 'https://coverr.co', cat: 'free', tag: '视频' },
  { name: 'Humaaans', desc: '免费可商用插画人物素材', url: 'https://www.humaaans.com', cat: 'free', tag: '插画' },
  { name: 'unDraw', desc: '免费开源插画素材，可自定义颜色', url: 'https://undraw.co', cat: 'free', tag: '插画' },
  { name: 'Icons8', desc: '免费图标/插画/音乐素材', url: 'https://icons8.com', cat: 'free', tag: '图标' },
  { name: 'Font Awesome', desc: '最流行的免费图标字体库', url: 'https://fontawesome.com', cat: 'free', tag: '图标' },
  { name: 'Google Fonts', desc: '免费商用 Web 字体库', url: 'https://fonts.google.com', cat: 'free', tag: '字体' },
  { name: 'Mori.Sam.Chen', desc: '免费可商用中文书法字体', url: 'https://www.morisamchen.com', cat: 'free', tag: '字体' },

  // ========== 图片处理 ==========
  { name: 'Remove.bg', desc: 'AI 一键去除背景', url: 'https://www.remove.bg', cat: 'image', tag: '去背景' },
  { name: 'TinyPNG', desc: '智能压缩 PNG/JPEG 图片', url: 'https://tinypng.com', cat: 'image', tag: '压缩', hot: true },
  { name: 'Squoosh', desc: 'Google 出品的在线图片压缩工具', url: 'https://squoosh.app', cat: 'image', tag: '压缩' },
  { name: 'Img2Go', desc: '在线图片格式转换/压缩/编辑', url: 'https://www.img2go.com', cat: 'image', tag: '转换' },
  { name: 'PicWish', desc: 'AI 图片处理：去背景/去水印/修复', url: 'https://picwish.com', cat: 'image', tag: 'AI' },
  { name: '佐糖', desc: '国产在线图片处理工具', url: 'https://www.zuotang.com', cat: 'image', tag: '去背景' },
  { name: 'Bigjpg', desc: 'AI 图片无损放大', url: 'https://bigjpg.com', cat: 'image', tag: '放大' },
  { name: 'waifu2x', desc: '二次元图片放大与降噪', url: 'https://waifu2x.udp.jp', cat: 'image', tag: '放大' },

  // ========== 在线工具 ==========
  { name: 'Smallpdf', desc: '在线 PDF 转换/压缩/编辑工具集', url: 'https://smallpdf.com', cat: 'tool', tag: 'PDF', hot: true },
  { name: 'iLovePDF', desc: 'PDF 在线处理工具', url: 'https://www.ilovepdf.com', cat: 'tool', tag: 'PDF' },
  { name: 'PDF24', desc: '免费 PDF 在线工具集', url: 'https://tools.pdf24.org', cat: 'tool', tag: 'PDF' },
  { name: '草料二维码', desc: '在线二维码生成器', url: 'https://cli.im', cat: 'tool', tag: '二维码' },
  { name: '在线 PS', desc: '在线版 Photoshop，免安装', url: 'https://www.photopea.com', cat: 'tool', tag: '设计' },
  { name: '腾讯文档', desc: '腾讯出品的在线协作文档/表格', url: 'https://docs.qq.com', cat: 'tool', tag: '办公' },
  { name: 'Convertio', desc: '在线文件格式转换器', url: 'https://convertio.io', cat: 'tool', tag: '转换' },
  { name: '在线正则测试', desc: '正则表达式在线测试工具', url: 'https://regex101.com', cat: 'tool', tag: '开发' },
  { name: 'MikuTools', desc: '聚合在线工具集', url: 'https://tools.miku.ac', cat: 'tool', tag: '聚合' },

  // ========== 营销/运营 ==========
  { name: '新榜', desc: '新媒体数据服务与排行榜', url: 'https://www.newrank.cn', cat: 'marketing', tag: '数据' },
  { name: '5118', desc: '关键词挖掘与内容营销工具', url: 'https://www.5118.com', cat: 'marketing', tag: 'SEO' },
  { name: '站长工具', desc: 'SEO 查询/网站检测工具集', url: 'https://tool.chinaz.com', cat: 'marketing', tag: 'SEO' },
  { name: '爱站网', desc: 'SEO 数据分析与关键词排名查询', url: 'https://www.aizhan.com', cat: 'marketing', tag: 'SEO' },
  { name: 'SimilarWeb', desc: '网站流量分析与竞品研究', url: 'https://www.similarweb.com', cat: 'marketing', tag: '分析' },
  { name: 'Google Analytics', desc: 'Google 网站流量统计分析', url: 'https://analytics.google.com', cat: 'marketing', tag: '分析' },
  { name: '百度统计', desc: '百度网站流量分析工具', url: 'https://tongji.baidu.com', cat: 'marketing', tag: '分析' },
  { name: '灰豚数据', desc: '抖音数据分析平台', url: 'https://www.huitun.com', cat: 'marketing', tag: '短视频' },
  { name: '蝉妈妈', desc: '抖音/小红书电商数据分析', url: 'https://www.chanmama.com', cat: 'marketing', tag: '电商' },

  // ========== AI 工具（新增） ==========
  { name: '智谱清言', desc: '智谱 AI 出品，基于 GLM 模型的中文 AI 助手', url: 'https://chatglm.cn', cat: 'ai', tag: '对话', hot: true },
  { name: '讯飞星火', desc: '科大讯飞出品的大语言模型，支持多模态', url: 'https://xinghuo.xfyun.cn', cat: 'ai', tag: '对话' },
  { name: '天工 AI', desc: '昆仑万维出品，支持搜索增强的 AI 助手', url: 'https://www.tiangong.cn', cat: 'ai', tag: '对话' },
  { name: '百川智能', desc: '王小川创立的 AI 助手，擅长中文理解', url: 'https://www.baichuan-ai.com', cat: 'ai', tag: '对话' },
  { name: '腾讯混元', desc: '腾讯出品的 AI 大模型，集成在微信中', url: 'https://hunyuan.tencent.com', cat: 'ai', tag: '对话' },
  { name: '文心一格', desc: '百度的 AI 绘画工具，中文描述生成图片', url: 'https://yige.baidu.com', cat: 'ai', tag: '绘画' },
  { name: 'Poe', desc: '聚合 ChatGPT/Claude/Gemini 等模型的对话平台', url: 'https://poe.com', cat: 'ai', tag: '聚合', hot: true },
  { name: 'Cursor', desc: 'AI 原生代码编辑器，内置智能补全与对话', url: 'https://cursor.sh', cat: 'ai', tag: '编程', hot: true },
  { name: 'GitHub Copilot', desc: 'AI 编程助手，代码自动补全与生成', url: 'https://github.com/features/copilot', cat: 'ai', tag: '编程' },
  { name: 'Suno', desc: 'AI 音乐生成工具，通过文字描述创作歌曲', url: 'https://suno.com', cat: 'ai', tag: '音乐' },
  { name: '海螺 AI', desc: 'MiniMax 出品的 AI 视频生成工具', url: 'https://hailuoai.com', cat: 'ai', tag: '视频' },
  { name: 'Pika', desc: 'AI 视频生成与编辑工具', url: 'https://pika.art', cat: 'ai', tag: '视频' },
  { name: 'Napkin AI', desc: 'AI 一键将文字转化为信息图/流程图', url: 'https://www.napkin.ai', cat: 'ai', tag: '办公' },

  // ========== 设计资源（新增） ==========
  { name: '创客贴', desc: '国内在线平面设计平台，模板极丰富', url: 'https://www.chuangkit.com', cat: 'design', tag: '平面' },
  { name: '图怪兽', desc: '在线图片编辑与模板设计平台', url: 'https://www.guaishou.com', cat: 'design', tag: '平面' },
  { name: 'Mockplus', desc: '国产原型设计工具，快速制作 APP 原型', url: 'https://www.mockplus.cn', cat: 'design', tag: 'UI' },
  { name: '即时设计', desc: '国产在线 UI 设计协作平台', url: 'https://js.design', cat: 'design', tag: 'UI' },
  { name: '字由', desc: '海量中文字体管理与使用工具', url: 'https://www.hellofont.cn', cat: 'design', tag: '字体' },
  { name: 'Huaban', desc: '花瓣网，设计灵感与素材采集平台', url: 'https://huaban.com', cat: 'design', tag: '灵感' },
  { name: '站酷', desc: '国内设计师社区，优秀作品展示', url: 'https://www.zcool.com.cn', cat: 'design', tag: '社区' },
  { name: 'Dribbble', desc: '全球设计师作品展示社区', url: 'https://dribbble.com', cat: 'design', tag: '社区' },
  { name: 'Behance', desc: 'Adobe 旗下设计师作品展示平台', url: 'https://www.behance.net', cat: 'design', tag: '社区' },

  // ========== 开发工具（新增） ==========
  { name: 'Docker', desc: '容器化平台，打包与部署应用的行业标准', url: 'https://www.docker.com', cat: 'dev', tag: '容器' },
  { name: 'MySQL', desc: '最流行的开源关系型数据库', url: 'https://www.mysql.com', cat: 'dev', tag: '数据库' },
  { name: 'MongoDB', desc: '开源 NoSQL 文档数据库', url: 'https://www.mongodb.com', cat: 'dev', tag: '数据库' },
  { name: 'Redis', desc: '高性能内存缓存数据库', url: 'https://redis.io', cat: 'dev', tag: '数据库' },
  { name: 'Nginx', desc: '高性能 Web 服务器与反向代理', url: 'https://nginx.org', cat: 'dev', tag: '服务器' },
  { name: 'PM2', desc: 'Node.js 进程管理工具', url: 'https://pm2.keymetrics.io', cat: 'dev', tag: '运维' },
  { name: 'Figma Dev Mode', desc: 'Figma 开发者模式，便捷查看设计标注', url: 'https://www.figma.com', cat: 'dev', tag: '协作' },
  { name: 'Insomnia', desc: '开源 API 调试与测试工具', url: 'https://insomnia.rest', cat: 'dev', tag: 'API' },
  { name: 'Python', desc: '最流行的编程语言之一，AI/数据科学首选', url: 'https://www.python.org', cat: 'dev', tag: '语言' },
  { name: 'Node.js', desc: 'JavaScript 运行时，构建高性能后端', url: 'https://nodejs.org', cat: 'dev', tag: '语言' },

  // ========== 在线学习（新增） ==========
  { name: '极客时间', desc: 'IT 领域付费课程平台，讲师均为业内专家', url: 'https://time.geekbang.org', cat: 'learn', tag: '编程', hot: true },
  { name: '得到', desc: '知识付费平台，涵盖商业/科技/人文等', url: 'https://www.dedao.cn', cat: 'learn', tag: '综合' },
  { name: '网易云课堂', desc: '网易出品的综合学习平台', url: 'https://study.163.com', cat: 'learn', tag: '综合' },
  { name: '腾讯课堂', desc: '腾讯出品的在线教育平台', url: 'https://ke.qq.com', cat: 'learn', tag: '综合' },
  { name: '牛客网', desc: '程序员笔试面试刷题与求职平台', url: 'https://www.nowcoder.com', cat: 'learn', tag: '求职' },
  { name: '力扣中国', desc: 'LeetCode 中文站，算法面试刷题', url: 'https://leetcode.cn', cat: 'learn', tag: '算法' },
  { name: 'GitHub Learning Lab', desc: 'GitHub 官方交互式学习平台', url: 'https://lab.github.com', cat: 'learn', tag: '编程' },
  { name: 'Roadmap.sh', desc: '开发者学习路线图，规划技能树', url: 'https://roadmap.sh', cat: 'learn', tag: '规划', hot: true },
  { name: 'DevOps Roadmap', desc: 'DevOps 工程师完整学习路径', url: 'https://roadmap.sh/devops', cat: 'learn', tag: '运维' },

  // ========== 效率工具（新增） ==========
  { name: 'Obsidian', desc: '本地优先的知识管理与笔记应用', url: 'https://obsidian.md', cat: 'productivity', tag: '笔记', hot: true },
  { name: 'Logseq', desc: '开源大纲式知识管理工具', url: 'https://logseq.com', cat: 'productivity', tag: '笔记' },
  { name: '幕布', desc: '极简大纲笔记，一键生成思维导图', url: 'https://mubu.com', cat: 'productivity', tag: '笔记' },
  { name: 'uTools', desc: '效率启动器，集成搜索/翻译/计算等插件', url: 'https://u.tools', cat: 'productivity', tag: '启动器', hot: true },
  { name: 'Quicker', desc: 'Windows 效率工具，快捷动作面板', url: 'https://getquicker.net', cat: 'productivity', tag: '启动器' },
  { name: 'Listary', desc: 'Windows 文件搜索与快速启动', url: 'https://www.listary.com', cat: 'productivity', tag: '搜索' },
  { name: 'Wox', desc: 'Windows 开源快捷启动器', url: 'https://wox.one', cat: 'productivity', tag: '启动器' },
  { name: 'CopyTranslator', desc: '翻译利器，选中即译', url: 'https://copytranslator.github.io', cat: 'productivity', tag: '翻译' },
  { name: 'Clash Verge', desc: '跨平台代理客户端', url: 'https://github.com/clash-verge-rev/clash-verge-rev', cat: 'productivity', tag: '网络' },

  // ========== 写作创作（新增） ==========
  { name: '火山写作', desc: '字节出品的 AI 中文写作助手', url: 'https://www.writingo.net', cat: 'writing', tag: 'AI' },
  { name: '写作猫', desc: 'AI 辅助中文写作工具', url: 'https://xiezuocat.com', cat: 'writing', tag: 'AI' },
  { name: '讯飞听见', desc: '语音转文字，会议录音整理', url: 'https://www.iflyrec.com', cat: 'writing', tag: '语音' },
  { name: '剪映图文', desc: '剪映的文字转视频功能', url: 'https://www.capcut.cn', cat: 'writing', tag: '视频' },
  { name: '秘塔写作', desc: 'AI 辅助写作与内容生成', url: 'https://metaso.cn', cat: 'writing', tag: 'AI' },

  // ========== 免费素材（新增） ==========
  { name: 'Storyset', desc: '免费可商用插画，可自定义颜色与风格', url: 'https://storyset.com', cat: 'free', tag: '插画' },
  { name: 'ManyPixels', desc: '免费开源插画库，支持 PNG/SVG 下载', url: 'https://www.manypixels.co', cat: 'free', tag: '插画' },
  { name: 'LottieFiles', desc: '免费 Lottie 动画素材库', url: 'https://lottiefiles.com', cat: 'free', tag: '动画' },
  { name: 'Freesound', desc: '免费音效与音乐素材社区', url: 'https://freesound.org', cat: 'free', tag: '音效' },
  { name: '中国色', desc: '中国传统颜色配色参考', url: 'http://zhongguose.com', cat: 'free', tag: '配色' },

  // ========== 图片处理（新增） ==========
  { name: 'ILoveIMG', desc: '在线批量图片压缩/调整/裁剪', url: 'https://www.iloveimg.com', cat: 'image', tag: '压缩' },
  { name: 'ImgURL', desc: '免费图床服务，图片外链托管', url: 'https://imgurl.org', cat: 'image', tag: '图床' },
  { name: 'SM.MS', desc: '免费图片托管与分享服务', url: 'https://sm.ms', cat: 'image', tag: '图床' },
  { name: '水印管家', desc: '在线批量给图片加水印', url: 'https://www.watermark.wang', cat: 'image', tag: '水印' },

  // ========== 在线工具（新增） ==========
  { name: '临时邮箱', desc: '一次性临时邮箱，保护隐私', url: 'https://www.linshiyouxiang.net', cat: 'tool', tag: '隐私' },
  { name: 'Temp Mail', desc: '国外临时邮箱服务', url: 'https://temp-mail.org', cat: 'tool', tag: '隐私' },
  { name: '在线计算器', desc: '多功能在线科学计算器', url: 'https://web2.0calc.com', cat: 'tool', tag: '计算' },
  { name: 'ProcessOn 作图', desc: '在线流程图/思维导图/UML 图', url: 'https://www.processon.com', cat: 'tool', tag: '作图' },
  { name: 'Excalidraw', desc: '开源在线白板，手绘风格图表', url: 'https://excalidraw.com', cat: 'tool', tag: '作图' },
  { name: '石墨表单', desc: '在线表单与问卷制作', url: 'https://shimo.im/forms', cat: 'tool', tag: '表单' },
  { name: '在线录屏', desc: '浏览器端在线录制屏幕', url: 'https://www.screencastify.com', cat: 'tool', tag: '录屏' },
  { name: 'ipip.net', desc: 'IP 地址查询与网络工具', url: 'https://www.ipip.net', cat: 'tool', tag: '网络' },
  { name: 'Speedtest', desc: '在线网速测试', url: 'https://www.speedtest.net', cat: 'tool', tag: '网络' },

  // ========== 营销运营（新增） ==========
  { name: '巨量算数', desc: '抖音趋势分析与热点追踪', url: 'https://trendinsight.oceanengine.com', cat: 'marketing', tag: '短视频' },
  { name: '百度指数', desc: '百度搜索热度趋势分析', url: 'https://index.baidu.com', cat: 'marketing', tag: '数据' },
  { name: '微信指数', desc: '微信搜索热度趋势', url: 'https://wx.qq.com', cat: 'marketing', tag: '数据' },
  { name: '头条指数', desc: '今日头条热度趋势分析', url: 'https://www.toutiao.com', cat: 'marketing', tag: '数据' },
  { name: 'SEMrush', desc: '全球 SEO 与竞品分析工具', url: 'https://www.semrush.com', cat: 'marketing', tag: 'SEO' },
  { name: 'Ahrefs', desc: '专业 SEO 分析与外链研究工具', url: 'https://ahrefs.com', cat: 'marketing', tag: 'SEO' },
  { name: '神策数据', desc: '用户行为分析与数据运营平台', url: 'https://www.sensorsdata.cn', cat: 'marketing', tag: '分析' },
  { name: 'GrowingIO', desc: '增长分析与用户运营平台', url: 'https://www.growingio.com', cat: 'marketing', tag: '分析' },
];

const categories = [
  { id: 'ai', name: 'AI 工具', icon: '🤖', desc: '对话、绘画、视频、办公等 AI 产品' },
  { id: 'design', name: '设计资源', icon: '🎨', desc: '平面/UI 设计工具、图库、图标、配色' },
  { id: 'dev', name: '开发工具', icon: '💻', desc: '代码托管、编辑器、部署、API 工具' },
  { id: 'learn', name: '在线学习', icon: '📚', desc: '课程平台、编程教程、技术社区' },
  { id: 'productivity', name: '效率工具', icon: '⚡', desc: '笔记、协作、待办、浏览器增强' },
  { id: 'writing', name: '写作创作', icon: '✍️', desc: '写作助手、翻译、文案、排版' },
  { id: 'image', name: '图片处理', icon: '🖼️', desc: '去背景、压缩、放大、格式转换' },
  { id: 'free', name: '免费素材', icon: '🎁', desc: '免费可商用的图片/视频/插画/字体' },
  { id: 'tool', name: '在线工具', icon: '🔧', desc: 'PDF、转换、二维码、办公工具' },
  { id: 'marketing', name: '营销运营', icon: '📊', desc: 'SEO、数据分析、新媒体运营' },
];
